include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # A public SDK documents every public member.
    public_member_api_docs: error
  exclude:
    - example/build/**
    - build/**
    - android/**
    - ios/**

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_positional_boolean_parameters
    - cancel_subscriptions
    - comment_references
    - directives_ordering
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - public_member_api_docs
    - require_trailing_commas
    - sort_pub_dependencies
    - throw_in_finally
    - unawaited_futures
    - unnecessary_lambdas
    - use_super_parameters
